### ISSUE TITLE
async

### ISSUE THREAD

**Issue by YIYOIY** [MaLuns/bcommentjs#1]

**Comment by MaLuns** [comment]
如果你已经部署好了 [bcommentjs](https://github.com/MaLuns/bcommentjs)

只需要在 你的博客主题配置文件里
``` yaml
comment:
  enable: true
  bComments:
    v: 0.0.13
    env: 你的云环境ID
```
